Incorrect

Promise.reject(new Error('I will reject!')).catch(err => {
                                                  ~~~ Prefer the safe `: unknown` for a `catch` callback variable.
  console.log(err);
});

Promise.reject(new Error('I will reject!')).catch((err: any) => {
                                                   ~~~~~~~~ Prefer the safe `: unknown` for a `catch` callback variable.
  console.log(err);
});

Promise.reject(new Error('I will reject!')).catch((err: Error) => {
                                                   ~~~~~~~~~~ Prefer the safe `: unknown` for a `catch` callback variable.
  console.log(err);
});

Promise.reject(new Error('I will reject!')).then(
  result => {
    console.log(result);
  },
  err => {
  ~~~ Prefer the safe `: unknown` for a `then` rejection callback variable.
    console.log(err);
  },
);

Correct

Promise.reject(new Error('I will reject!')).catch((err: unknown) => {
  console.log(err);
});
